// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attributes struct {
	Age         *float64  `json:"Age"`
	Gender      *string   `json:"Gender"`
	Smile       *float64  `json:"Smile"`
	Moustache   *float64  `json:"Moustache"`
	Beard       *float64  `json:"Beard"`
	Sideburns   *float64  `json:"Sideburns"`
	Glasses     *string   `json:"Glasses"`
	Emotion     *Emotion  `json:"Emotion"`
	HairColor   *string   `json:"HairColor"`
	EyeMakeup   *bool     `json:"EyeMakeup"`
	LipMakeup   *bool     `json:"LipMakeup"`
	Accessories []*string `json:"Accessories"`
	Blur        *float64  `json:"Blur"`
	Exposure    *float64  `json:"Exposure"`
	Noise       *float64  `json:"Noise"`
}

type Coordinate struct {
	X float64 `json:"X"`
	Y float64 `json:"Y"`
}

type DetectedFace struct {
	FaceID         string      `json:"FaceID"`
	FaceRectangle  *Rectangle  `json:"FaceRectangle"`
	FaceLandmarks  *Landmarks  `json:"FaceLandmarks"`
	FaceAttributes *Attributes `json:"FaceAttributes"`
}

type Emotion struct {
	Anger     float64 `json:"Anger"`
	Contempt  float64 `json:"Contempt"`
	Disgust   float64 `json:"Disgust"`
	Fear      float64 `json:"Fear"`
	Happiness float64 `json:"Happiness"`
	Neutral   float64 `json:"Neutral"`
	Sadness   float64 `json:"Sadness"`
	Surprise  float64 `json:"Surprise"`
}

type Landmarks struct {
	PupilLeft           *Coordinate `json:"PupilLeft"`
	PupilRight          *Coordinate `json:"PupilRight"`
	NoseTip             *Coordinate `json:"NoseTip"`
	MouthLeft           *Coordinate `json:"MouthLeft"`
	MouthRight          *Coordinate `json:"MouthRight"`
	EyebrowLeftOuter    *Coordinate `json:"EyebrowLeftOuter"`
	EyebrowLeftInner    *Coordinate `json:"EyebrowLeftInner"`
	EyeLeftOuter        *Coordinate `json:"EyeLeftOuter"`
	EyeLeftTop          *Coordinate `json:"EyeLeftTop"`
	EyeLeftBottom       *Coordinate `json:"EyeLeftBottom"`
	EyeLeftInner        *Coordinate `json:"EyeLeftInner"`
	EyebrowRightInner   *Coordinate `json:"EyebrowRightInner"`
	EyebrowRightOuter   *Coordinate `json:"EyebrowRightOuter"`
	EyeRightInner       *Coordinate `json:"EyeRightInner"`
	EyeRightTop         *Coordinate `json:"EyeRightTop"`
	EyeRightBottom      *Coordinate `json:"EyeRightBottom"`
	EyeRightOuter       *Coordinate `json:"EyeRightOuter"`
	NoseRootLeft        *Coordinate `json:"NoseRootLeft"`
	NoseRootRight       *Coordinate `json:"NoseRootRight"`
	NoseLeftAlarTop     *Coordinate `json:"NoseLeftAlarTop"`
	NoseRightAlarTop    *Coordinate `json:"NoseRightAlarTop"`
	NoseLeftAlarOutTip  *Coordinate `json:"NoseLeftAlarOutTip"`
	NoseRightAlarOutTip *Coordinate `json:"NoseRightAlarOutTip"`
	UpperLipTop         *Coordinate `json:"UpperLipTop"`
	UpperLipBottom      *Coordinate `json:"UpperLipBottom"`
	UnderLipTop         *Coordinate `json:"UnderLipTop"`
	UnderLipBottom      *Coordinate `json:"UnderLipBottom"`
}

type Rectangle struct {
	Width  int `json:"Width"`
	Height int `json:"Height"`
	Top    int `json:"Top"`
	Left   int `json:"Left"`
}
